flx-ido does not exist but flx does
I had to change flx-ido to flx to avoid the following:

error: Package `flx-ido' is not available for installation